### ISSUE TITLE
Dynatrace Jenkins Plugin - Docker/Container Configuration Validation

### ISSUE THREAD

**Issue by dhiebert** [jenkinsci/dynatrace-plugin#2] opened 2016-11-03 20:39 UTC
**High Level Description:**
We are trying to shift left CI performance characteristics into our unit test phase, we are using a simple common utility java app to demo/highlight/prototype these performance characteristics. 
**We used these instructions **
https://github.com/jenkinsci/dynatrace-plugin/blob/master/README.md

**Nuance:**  
 Our build system is a Docker/Container system, hence the hostname is unique every build and we have to unpack the DT agent at build time. 

We had a problem noted where the corridor was not getting built on the DT server.  So we tested our hypothesis and use the following static value, we started getting the corridor built now for the <argLine> we appended overridehostname=dantest.   

**Problem Description:**
 In testing Option 1 and Option 2 (from instructions above), the only remaining issue we encounter is that the Dynatrace Jenkins Plugin  does not seem to be getting the result performance values back correctly.  Hence we do not think the DT Jenkins build will fail and/or graphic data for degradation, volatile, improved will not show correctly. The error is slightly different between Option 1 and Option 2 (but we tested both configurations). 

**Option 1 Jenkins:**  It seems to gather the data, register the build increment the # but the previous build/next build does not seem to have data and I suspect degradation, improved, volatile, will show any data.  I have tried throwing in a Thread.sleep(3000)  in a java method and we see no performance on degradation on Dynatrace Jenkins plugin. 

Option 1 - Build #344
Tests run: 8, Failures: 0, Errors: 0, Skipped: 2, Time **elapsed: 0.587 sec** - in HostUtilsTest
Running StringUtilsTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time **elapsed: 0 sec** - in StringUtilsTest

Option 1 - Build #345
Running HostUtilsTest
Tests run: 8, Failures: 0, Errors: 0, Skipped: 2, Time elapsed: 15.352 sec - in HostUtilsTest
Running StringUtilsTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 8.991 sec - in StringUtilsTest
.....
Dynatrace AppMon Plugin - build tear down...
Deleting 1 temporary files
channel stopped
Sleeping for the configured delay of 10 seconds before retrieving test run data from Dynatrace Server...
Connecting to Dynatrace Server REST interface... (ID=xxxx-xxxx-xxxxxx-xxxxxx-xxx)
Report summary: {Failed=0, Degraded=0, Volatile=0, Improved=0, Passed=9}.
Finished: SUCCESS

**Option 2 Maven/Jenkins:** It seems that appmon agent on jenkins build sever does not return any data, and no graphic/trend data is generated. Additionally, in log file it seems that the dtRunID is not getting to the post action jenkins process to retrieve data from the server. 

**(Logs available upon request)**  ... 
IMO everything looks good optionTestRunIdJava gets generated before run and passed to run  on argline to agent... you can see it at multiple places in DT native run info  and then finally in log...it is like it loosed the optionTestRunIdJava 
Dynatrace AppMon Plugin - build tear down...
Deleting 1 temporary files
channel stopped
Sleeping for the configured delay of 10 seconds before retrieving test run data from Dynatrace Server...
Connecting to Dynatrace Server REST interface...
The test runs don't contain any test execution!
Sleeping for the configured delay of 10 seconds before retrieving test run data from Dynatrace Server... re-try 1 out of 3
Connecting to Dynatrace Server REST interface...
The test runs don't contain any test execution!
Sleeping for the configured delay of 10 seconds before retrieving test run data from Dynatrace Server... re-try 2 out of 3
Connecting to Dynatrace Server REST interface...
The test runs don't contain any test execution!
Sleeping for the configured delay of 10 seconds before retrieving test run data from Dynatrace Server... re-try 3 out of 3
Connecting to Dynatrace Server REST interface...
The test runs don't contain any test execution!
Fetching data from Dynatrace Server REST interface failed
java.util.NoSuchElementException: No matching test run with test executions has been recorded by the configured Dynatrace Server
Finished: SUCCESS

**Comment by SonjaChevre** [comment] 2016-11-10 09:57
for **Option 1 Jenkins**: 
the report summary shows {Failed=0, Degraded=0, Volatile=0, Improved=0, Passed=9} - is this the same result you are seeing in the Test Automation Dashlet?

Or are you seeing a different result in the Test Automation Dashlet?

**Comment by dhiebert** [comment] 2016-11-14 15:19
We checked Friday, it does appear(in case of Option 1) the Test Automation Dashlet {Failed=0, Degraded=0, Volatile=0, Improved=0, Passed=9} is relaying the same results.  Even though our corridor is built, when we introduce a thread.sleep in code, which cascades to our other methods, the Test Automation Dashlet, or Jenkins DT plugin, never report "degraded" or "improved" after removed in those parm values.  We are investigating further, our hope is that perhaps resolving the issue on the Test Automation Dashlet will resolve our Jenkins plugin issue.   Will keep you posted.  Thx!

**Comment by SonjaChevre** [comment] 2016-11-16 10:09
Makes sense as Jenkins use the same data (through the test automation rest api, see https://community.dynatrace.com/community/display/DOCDT65/REST+Interfaces+for+Test+Automation) 

As soon as the status problem is fixed in the Test Automation Dashlet, the problem should also be fixed in Jenkins. I would recommend looking into the Test Automation Settings (System Profile settings / Test Automation). There are a couple of settings that influence how quickly the corridor react to changes. If this doesn't help, feel free to open a support ticket including a session export - as the test automation dashlet (and corridor calculation) is covered by the standard support.

The problem with "Option 2 Maven/Jenkins" might be the usage / configuration of a different system profile. E.g. if you register the testrun for system profile x (define in Maven), but the agents connects to system profile y, you won't get any test result data for that test run.

Hope that helps!
Sonja

**Comment by dhiebert** [comment] 2016-11-29 21:39
Quick Update on Option 1:  
We started correlating the resulting graph data on the jenkins plugin and the test automation dashlet.  We noted that we were only getting pass/fails on both view verses the performance characteristics we were hoping/expecting.   I went back to the step, "Dynatrace AppMon - Register Test Run" and noted we had set the category  to "unit",  we changed to "performance" and then we started to get the expected results on both the dashlet and the jenkins plugin.    

I guess only recommendation would be to provide a description onto how each category influences the resulting effect on the Jenkins plugin, since it appears "unit" tests only relay "pass/fail"  and since we were looking for degraded, volatility, and improved.  I think it even returns those values but they are zero'd out when getting pushed to the Jenkins Dynatrace Plugin. 

Cool Tech: 
We split off a Jenkins, maven project to trigger after the successful unit test build, there-by grouping specific performance categorized tests.   Using the Jenkins Dynatrace Plugin with a specific performance maven build profile, and running a subset of specific performance categorized junit tests with the Dynatrace Agent.  Now every time a commit is delivered by a developer, we run the unit tests and then trigger a performance run in which we can fail the build when performance degrades or even set to unstable when volatility ensues.    

Thanks!

**Comment by SonjaChevre** [comment] 2016-12-01 08:42
thanks for the feedback! Unit test captures a smaller set of metrics than performance tests (see also https://community.dynatrace.com/community/pages/viewpage.action?pageId=221381168#Unit/IntegrationandPerformanceTests-Measures). It might be the reason why you didn't get any regressions and you did with the performance metrics.

Anyway, happy it is working for you now :)

**Closed** 2016-12-01 08:43 UTC
Labels: question
